# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.IntegerField(help_text='Enter in Integer Format')),
                ('team_2_score', models.IntegerField(help_text='Enter in Integer Format')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Singles'), (1, 'Doubles')])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Enter as Text. Maximum Length:30', max_length=30, unique=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstplayers', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(blank=True, help_text='If Singles, leave this empty', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondplayers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(help_text='object in Teams DB', on_delete=django.db.models.deletion.CASCADE, related_name='firstteams', to='tracker.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(help_text='object in Teams DB', on_delete=django.db.models.deletion.CASCADE, related_name='secondteams', to='tracker.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='tracker.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Match'),
        ),
    ]
