# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180109_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team1_score',
            new_name='team_1_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team2_score',
            new_name='team_2_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1',
            new_name='team_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2',
            new_name='team_2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='user1',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='user2',
            new_name='user_2',
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Singles'), (1, 'Doubles')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 8, 1, 28, 899000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 8, 1, 28, 899000, tzinfo=utc)),
        ),
    ]
