# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180109_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ended_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
