# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180109_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_name',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(help_text='Choose team 1 of your category', on_delete=django.db.models.deletion.CASCADE, related_name='firstteams', to='tracker.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(help_text='Choose team 2 of your category', on_delete=django.db.models.deletion.CASCADE, related_name='secondteams', to='tracker.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(help_text='If Singles, enter same name as user 1', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_2',
            field=models.ForeignKey(blank=True, help_text='If Singles, leave this empty', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondplayers', to=settings.AUTH_USER_MODEL),
        ),
    ]
